resources:
  - ../../../base/namespaces.yaml
  - ../../../base/istio.yaml
  - ../../../base/istiocni.yaml
  - ../../../base/gateway.yaml
  - ../../../base/backend-melbourne.yaml
  - ../../../base/httproute-melbourne.yaml
  - clusterissuer.yaml
  - dnspolicy.yaml
  - tlspolicy.yaml
commonLabels:
  location: melbourne
