apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - backend.yaml
  - httproute.yaml
  - clusterissuer.yaml
  - dnspolicy.yaml
  - tlspolicy.yaml
labels:
  - pairs:
      location: melbourne
configMapGenerator:
  - name: domain-config
    envs:
      - domain-config.env
generatorOptions:
  disableNameSuffixHash: true
replacements:
  - source:
      kind: ConfigMap
      name: domain-config
      fieldPath: data.HOSTNAME
    targets:
      - select:
          kind: Gateway
          name: shared-app-gw
          namespace: api-gateway
        fieldPaths:
          - spec.listeners.0.hostname
      - select:
          kind: HTTPRoute
          name: shared-app-route
          namespace: demo-app
        fieldPaths:
          - spec.hostnames.0
