apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - istio-system-namespace.yaml
  - istio-cni-namespace.yaml
  - api-gateway-namespace.yaml
  - demo-app-namespace.yaml
  - istio.yaml
  - istiocni.yaml
  - gateway.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: rhcl-rosa-demo
