apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - ../../../base/backend-melbourne.yaml
  - ../../../base/httproute-melbourne.yaml
  - clusterissuer.yaml
  - dnspolicy.yaml
  - tlspolicy.yaml
commonLabels:
  location: melbourne
