#!/usr/bin/env bash
# install-operators.sh
#
# Creates the cert-manager operator IAM roles for both ROSA clusters (required
# on ROSA STS before OperatorHub install), then applies the operator Kustomize
# overlays to both clusters.
#
# Usage:
#   DOMAIN=$DOMAIN ./scripts/install-operators.sh
#   DOMAIN=$DOMAIN HOSTED_ZONE_ID=$HOSTED_ZONE_ID ./scripts/install-operators.sh
#
# What this installs (via Kustomize) on BOTH clusters:
#   - Red Hat Connectivity Link
#   - Red Hat OpenShift Service Mesh 3
#   - cert-manager Operator for Red Hat OpenShift
#
# The cert-manager Subscription is patched with the cluster-specific ROLEARN
# generated by create-cert-manager-operator-role.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
if [[ -z "${DOMAIN:-}" ]]; then
  echo "Error: DOMAIN environment variable is required."
  echo "Usage: DOMAIN=<base-domain> $0"
  exit 1
fi

# ---------------------------------------------------------------------------
# Resolve hosted zone (needed by create-cert-manager-operator-role.sh)
# ---------------------------------------------------------------------------
if [[ -z "${HOSTED_ZONE_ID:-}" ]]; then
  echo "Resolving HOSTED_ZONE_ID from DOMAIN=${DOMAIN} ..."
  HOSTED_ZONE_ID="$("${SCRIPT_DIR}/resolve-hosted-zone-id.sh" "${DOMAIN}")"
fi
echo "Using HOSTED_ZONE_ID=${HOSTED_ZONE_ID}"
export HOSTED_ZONE_ID

# ---------------------------------------------------------------------------
# Step 1: Create cert-manager operator IAM roles for both clusters.
#
# On ROSA STS the cert-manager OperatorHub install dialog requires a role ARN
# *before* the operator is installed. The roles are created here and their ARNs
# are injected into the Subscription manifests via envsubst in step 2.
# ---------------------------------------------------------------------------
echo
echo "================================================================"
echo " Step 1: Creating cert-manager operator IAM roles"
echo "================================================================"

declare -A CERT_MANAGER_ARNS

for CLUSTER in rosa-syd rosa-melb; do
  echo
  echo "--- ${CLUSTER} ---"
  ARN="$(
    DOMAIN="${DOMAIN}" \
    HOSTED_ZONE_ID="${HOSTED_ZONE_ID}" \
    "${SCRIPT_DIR}/create-cert-manager-operator-role.sh" \
      --cluster-name "${CLUSTER}" \
      --oc-context   "${CLUSTER}" \
    | grep -E '^arn:aws:iam::' | tail -1
  )"

  if [[ -z "${ARN}" ]]; then
    echo "Error: could not determine role ARN for ${CLUSTER}." >&2
    echo "Run the following manually and check for errors:" >&2
    echo "  DOMAIN=${DOMAIN} ./scripts/create-cert-manager-operator-role.sh \\" >&2
    echo "    --cluster-name ${CLUSTER} --oc-context ${CLUSTER}" >&2
    exit 1
  fi

  CERT_MANAGER_ARNS["${CLUSTER}"]="${ARN}"
  echo "Role ARN for ${CLUSTER}: ${ARN}"
done

# ---------------------------------------------------------------------------
# Step 2: Apply the operator overlays to each cluster.
#
# CERT_MANAGER_OPERATOR_ROLE_ARN is exported so that envsubst can substitute
# the placeholder in the cert-manager Subscription patch inside the overlay.
# ---------------------------------------------------------------------------
echo
echo "================================================================"
echo " Step 2: Applying operator Kustomize overlays"
echo "================================================================"

declare -A OVERLAYS=(
  [rosa-syd]="${REPO_ROOT}/manifests/operators/overlays/sydney"
  [rosa-melb]="${REPO_ROOT}/manifests/operators/overlays/melbourne"
)

for CLUSTER in rosa-syd rosa-melb; do
  OVERLAY="${OVERLAYS[${CLUSTER}]}"
  export CERT_MANAGER_OPERATOR_ROLE_ARN="${CERT_MANAGER_ARNS[${CLUSTER}]}"

  echo
  echo "--- Applying operators overlay to ${CLUSTER} ---"
  echo "    Overlay : ${OVERLAY}"
  echo "    ROLEARN : ${CERT_MANAGER_OPERATOR_ROLE_ARN}"

  TMP_RENDERED="$(mktemp)"
  trap 'rm -f "${TMP_RENDERED}"' EXIT

  oc kustomize "${OVERLAY}" \
    | envsubst '${CERT_MANAGER_OPERATOR_ROLE_ARN}' \
    > "${TMP_RENDERED}"

  oc --context="${CLUSTER}" apply -f "${TMP_RENDERED}"
  rm -f "${TMP_RENDERED}"
done

# ---------------------------------------------------------------------------
# Step 3: Print ARN summary for reference
# ---------------------------------------------------------------------------
echo
echo "================================================================"
echo " cert-manager operator role ARNs (for reference)"
echo "================================================================"
echo
echo "  rosa-syd : ${CERT_MANAGER_ARNS[rosa-syd]}"
echo "  rosa-melb: ${CERT_MANAGER_ARNS[rosa-melb]}"
echo
echo "These ARNs have been injected into the cert-manager Subscription"
echo "manifests that were just applied."
echo
echo "Next: wait for all three operators to reach InstallSucceeded on"
echo "both clusters, then continue with the deployment steps in README.md."
echo
echo "  oc --context=rosa-syd  get csv -n openshift-operators"
echo "  oc --context=rosa-syd  get csv -n cert-manager-operator"
echo "  oc --context=rosa-melb get csv -n openshift-operators"
echo "  oc --context=rosa-melb get csv -n cert-manager-operator"
