apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-cert-manager-operator
      namespace: cert-manager-operator
    patch: |-
      - op: replace
        path: /spec/config/env/0/value
        value: "${CERT_MANAGER_OPERATOR_ROLE_ARN}"
labels:
  - pairs:
      location: melbourne
    includeSelectors: false
    includeTemplates: true
